import { Inter } from 'next/font/google'
import './globals.css'
import { Suspense } from 'react'
import Footer from './components/Footer'
import loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Harsh Telang-Portfolio Site',
  Link: 'https://i.pinimg.com/474x/8c/50/99/8c5099722c87442fe959128945884e2e.jpg',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body >
        <Suspense fallback={<loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  )
}
