import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Harsh Telang-Portfolio Site',
  Link: 'https://i.pinimg.com/474x/8c/50/99/8c5099722c87442fe959128945884e2e.jpg',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body className={inter.className}>{children}
      <Footer />
      </body>
    </html>
  )
}
